name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: exam
          POSTGRES_PASSWORD: exam
          POSTGRES_DB: exam
        options: >-
          --health-cmd="pg_isready -U exam" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install --no-cache-dir -r requirements.txt
      - run: pytest
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: exam
          DB_PASSWORD: exam
          DB_NAME: exam

